food = input("Name a food: ")
plant = input("name a plant: ")
cooking = input("Name a method of cooking: ")
describe_food = input("What word describes burned food? ")
DIY = input("Name a DIY item: ")
print()
print()
print("MENU")
print(cooking, food, "With", describe_food,plant,"on a bed of ",DIY)