print("Getting to know you!")
myName = input("What's your name?: ")
myFavouriteFood = input("What's your favourite food: ")
myFavouriteMusic = input("Your favourite music: ")
WhereYouLive = input("Where do you live?: ")
print()
print()
print("You are")
print(myName)
print("You are probably hungry for")
print(myFavouriteFood)
print("and you're definitely getting your groove on to")
print(myFavouriteMusic)
print("living in the amazing")
print(WhereYouLive)